[package]
name = "smithay-egui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
egui = "0.16"
egui_glow = { version = "0.16", default-features = false }
lazy_static = { version = "1.4.0", optional = true }
slog = { version = "2.7.0", optional = true }

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "e41b450"
default-features = false
features = ["renderer_gl"]

[features]
default = ["default_fonts", "render_element"]
# Let egui bundle some fonts by default.
default_fonts = ["egui/default_fonts"]
render_element = ["smithay/desktop", "lazy_static", "slog"]

[dev-dependencies]
anyhow = "1.0"
egui_demo_lib = "0.16"

[dev-dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "e41b450"
default-features = false
features = ["renderer_gl", "backend_winit"]